//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsWhinker.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.courseContents = new HashSet<courseContent>();
        }
    
        public int idCourse { get; set; }
        public int idTypeCourse { get; set; }
        public string content1 { get; set; }
        public string content2 { get; set; }
        public Nullable<int> creditFee { get; set; }
        public string featuredImage { get; set; }
        public string requirements { get; set; }
        public bool status { get; set; }
        public string title { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string userCreation { get; set; }
        public System.DateTime dateChange { get; set; }
        public string userChange { get; set; }
    
        public virtual typeCourse typeCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courseContent> courseContents { get; set; }
    }
}
