//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsWhinker.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseContent
    {
        public int idCourseContent { get; set; }
        public Nullable<int> idCourse { get; set; }
        public Nullable<int> idContent { get; set; }
    
        public virtual content content { get; set; }
        public virtual course course { get; set; }
    }
}
