//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsWhinker.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public typeCourse()
        {
            this.courses = new HashSet<course>();
        }
    
        public int idTypeCourse { get; set; }
        public string Name { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string userCreation { get; set; }
        public System.DateTime dateChange { get; set; }
        public string userChange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course> courses { get; set; }
    }
}
